body_pos:
  gamma: 1.0
  lambda: 2.0
body_rot:
  gamma: 1.0
  lambda: 2.0
dof_pos:
  gamma: 1.0
  lambda: 2.0
body_vel:
  gamma: 1.0
  lambda: 1.0
body_ang_vel:
  gamma: 1.0
  lambda: 1.0
dof_vel:
  gamma: 1.0
  lambda: 1.0
object_pos:
  gamma: 1.0
  lambda: 2.0
object_rot:
  gamma: 1.0
  lambda: 2.0
relative_pos:
  gamma: 1.0
  lambda: 1.0
relative_rot:
  gamma: 1.0
  lambda: 1.0
contact:
  gamma: 1.0
  lambda: 2.0
regularization: 0.1
amp_weight: 0.5
