name: generic_humanoid
urdf: assets/robots/generic_humanoid.urdf
root_body: pelvis
joint_names:
  - torso_yaw
  - torso_pitch
  - left_hip_yaw
  - left_hip_roll
  - left_hip_pitch
  - left_knee
  - left_ankle_pitch
  - left_ankle_roll
  - right_hip_yaw
  - right_hip_roll
  - right_hip_pitch
  - right_knee
  - right_ankle_pitch
  - right_ankle_roll
  - left_shoulder_pitch
  - left_shoulder_roll
  - left_shoulder_yaw
  - left_elbow
  - left_wrist
  - right_shoulder_pitch
  - right_shoulder_roll
  - right_shoulder_yaw
  - right_elbow
  - right_wrist
contact_bodies:
  - left_hand
  - right_hand
  - left_foot
  - right_foot
key_bodies:
  - left_hand
  - right_hand
  - left_foot
  - right_foot
  - head
